### ISSUE TITLE
throttle a fast-ticking progress bar?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/progress#49]
What do you think about having a `throttle` argument, which controls how often the progress bar is updated on the screen?

Some tracked operations might occur very quickly, which could result in overly-fast updated to the progress bar on the screen. It would be nice to be able to say something like, 'only re-draw the progress bar every 0.1 seconds', or something similar.

**Comment by gaborcsardi** [comment]
By default it only redraws if the output looks different than the last one. This should take care of the  problem of too frequent problems, I believe. At least in most cases. Please reopen if you think otherwise.

**Comment by eliocamp** [comment]
Hi! I wanted to see something like this. The issue I have is that, because of the information I put in `format`, the progress bar does change at every step. 

So, for example, something like this:
```r
pb <- progress::progress_bar$new(format = ":current [:bar]")

for (i in 1:3000) {
  pb$tick()
  Sys.sleep(0.1)
}
```

will update at every step, I believe.

For that, I think that a way to throttle the progress bar would be nice. Personally, I would prefer to be set to update every nth tick, but in time units could also work.

**Comment by gaborcsardi** [comment]
Why don't you just tick every nth step then?

**Comment by eliocamp** [comment]
Is what I do, but it requires a fair amount of boilerplate code that would be nice to have built in:

```r
bar_tick <- 0
for (i in 1:N) {
  if (bar_tick == 0) {
    p_bar$update(i/N)
    bar_tick <- 500
  }
  bar_tick <- bar_tick - 1
}
```
